version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: guestbook
    ports:
      - '6432:5432'

  mailer:
    image: schickling/mailcatcher
    ports: [ 1025, 1080 ]